### ISSUE TITLE
在release模式打包，无法成功

### ISSUE THREAD

**Issue by flowYogi** [xuwening/react-native-debug-server-host#1]
Archive的错误报告：
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTDevMenuItem", referenced from:
      objc-class-ref in libDebugServerHost.a(DevServerAddr.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

` "_OBJC_CLASS_$_RCTDevMenuItem", referenced from:
      objc-class-ref in libDebugServerHost.a(DevServerAddr.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by xuwening** [comment]
忘记同步控制debug宏了，已经修改。
