### ISSUE TITLE
使用cocoapod方式集成后，没有出现Debug server host选项

### ISSUE THREAD

**Issue by iOSQiao** [xuwening/react-native-debug-server-host#2]
在react native为0.42.0的时候，
使用cocoapod方式集成后，没有出现Debug server host选项。

**Comment by xuwening** [comment]
请使用 0.2.5 版本（目前没有对低版本做兼容）。

**Comment by iOSQiao** [comment]
我修改好了，是因为方法已经修改了。

+ (void)load {
	RCTSwapInstanceMethods([RCTDevMenu class], @selector(menuItems), @selector(newMenuItems));
	static const DevServerAddress *devServerAddress;
	static dispatch_once_t onceToken;
	dispatch_once(&onceToken, ^{
		devServerAddress = [[DevServerAddress alloc] init];
	});
}
